//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnIT_QPJYCJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Felhasznalo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Felhasznalo()
        {
            this.FelhasznaloKurzus = new HashSet<FelhasznaloKurzu>();
            this.Mentetts = new HashSet<Mentett>();
        }
    
        public int ID { get; set; }
        public string VezetekNev { get; set; }
        public string KeresztNev { get; set; }
        public int Kor { get; set; }
        public string Email { get; set; }
        public string Jelszo { get; set; }
        public int EgyetemID { get; set; }
        public int Penz { get; set; }
    
        public virtual Egyetem Egyetem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FelhasznaloKurzu> FelhasznaloKurzus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mentett> Mentetts { get; set; }
    }
}
