//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnIT_QPJYCJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mentett
    {
        public int ID { get; set; }
        public int FelhasznaloID { get; set; }
        public bool Remember_me { get; set; }
        public bool Auto_login { get; set; }
    
        public virtual Felhasznalo Felhasznalo { get; set; }
    }
}
