//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnIT_QPJYCJ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatasEntities : DbContext
    {
        public DatasEntities()
            : base("name=DatasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ar> Ars { get; set; }
        public virtual DbSet<Egyetem> Egyetems { get; set; }
        public virtual DbSet<Felhasznalo> Felhasznaloes { get; set; }
        public virtual DbSet<FelhasznaloKurzu> FelhasznaloKurzus { get; set; }
        public virtual DbSet<Kurzu> Kurzus { get; set; }
        public virtual DbSet<Mentett> Mentetts { get; set; }
        public virtual DbSet<Targy> Targies { get; set; }
    }
}
