//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnIT_QPJYCJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Targy
    {
        public int ID { get; set; }
        public string Nev { get; set; }
    
        public virtual Kurzu Kurzu { get; set; }
    }
}
